'use strict';

export const SAVE_STATUS_SUCCESSFUL = 'SAVE_STATUS_SUCCESSFUL';
export const SAVE_STATUS_ERROR = 'SAVE_STATUS_ERROR';
export const SAVE_STATUS_UNKNOWN = 'SAVE_STATUS_UNKNOWN';
export const SAVE_STATUS_UNSAVED_CHANGES = 'SAVE_STATUS_UNSAVED_CHANGES';
export const SAVE_STATUS_ATTEMPTING = 'SAVE_STATUS_ATTEMPTING';

export const SETTINGS_STORAGE_PREFIX = 'homeassistantSettings'
export const SETTINGS_STORAGE_SERVER_URL_NAME = 'serverUrl'

export const LOAD_STATUS_ATTEMPTING = 'LOAD_STATUS_ATTEMPTING'
export const LOAD_STATUS_SUCCESS = 'LOAD_STATUS_SUCCESS'