'use strict';

export const UPDATE_URL_STATE = 'UPDATE_URL_STATE';
export const UPDATE_PASSWORD_STATE = 'UPDATE_PASSWORD_STATE';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_PASSOWRD = 'SAVE_PASSWORD';
export const RETRIEVE_PASSWORD = 'RETRIEVE_PASSWORD';

export const ADD_STATES_TO_STORE = 'ADD_STATES_TO_STORE';
export const FETCH_STATES_STATUS = 'FETCH_STATES_STATUS';

export const SET_NAVIGATION_PAGE = 'SET_NAVIGATION_PAGE';