export const UPDATE_URL_STATE = 'UPDATE_URL_STATE';
export const UPDATE_PASSWORD_STATE = 'UPDATE_PASSWORD_STATE';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const RETRIEVE_SETTINGS = 'RETRIEVE_SETTINGS';